### PR TITLE
Cleanup/refactor template content model impl

### PR DESCRIPTION
**Pull request by josecarlosgt**
Tested on a fresh instance. Further testing is recommended as this PR involves significant changes to the template content model implementation.

### CODE REVIEW

**Comment by jbarrera-xumak** [comment]
Can you do rebase from master please?

**Comment by josecarlosgt** [comment]
OK. This has been done now. Commits in this branch are now ahead of those currently in master.

**Comment by jbarrera-xumak** [comment]
Thanks, could you update the changelog file please?

**Comment by josecarlosgt** [comment]
Done. CHANGELOG file is updated in the previous commit.

**Comment by josecarlosgt** [comment]
Last update to the CHANGELOG was re-written to make it standard with other updates.

**Review by jbarrera-xumak — APPROVED** [review]
+1

**Pull request merged**
