### PR TITLE
reverted removed NumberUtils

### PR DESCRIPTION
**Pull request by nimsothea**

### CODE REVIEW

**Review by neozilon — CHANGES_REQUESTED** [review]
Why are we adding back the com.day.cq.cq-commons ? have you tried this using the nexus from tikal ? I believe this dependency is not available anymore instead we use the uber jar from adobe @nimsothea

**Comment by nimsothea** [comment]
It's not resolved for me. The uber-jar kept failing when running maven
install.

**Comment by neozilon** [comment]
@nimsothea that is because you somewhere probably in your settings.xml still have a reference to the old Nexus repository that contains old dependencies or are corrupted, make sure you are getting all your dependencies from repo.tikaltechnologies.io I have seen that issue in other installations , don't know why the old nexus has that issue. Because those dependencies are not available to everyone, we should not use them

**Comment by nimsothea** [comment]
@neozilon can you share your Maven's settings.xml.

**Comment by nimsothea** [comment]
@neozilon I reverted the pom.xml file.

**Comment by nimsothea** [comment]
@neozilon we merge this?

**Review by neozilon — APPROVED** [review]

**Pull request merged**
